#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 13 18:10:31 2018

@author: saanidhi
"""

import smtplib
#saanidhi version 
ss = smtplib.SMTP("smtp.gmail.com", 587)
ss.ehlo()
ss.starttls()
ss.login("saanidhi.1211@gmail.com", "password")

msg="Subject: Yello.\nTest mail"
ss.sendmail("saanidhi.1211@gmail.com" ,"Recievers email id",msg)
ss.close() 